# Uses https://github.com/crazy-max/ghaction-github-labeler
# You need to create a GITHUB_TOKEN secret with the correct permissions to be able to make changes to labels
# Manually run the Action in the GitHub UI to add Hazard Log Labels as per the YAML file

name: create-hazard-log-labels

on:
  workflow_dispatch

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Labeller
        if: success()
        uses: crazy-max/ghaction-github-labeler@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: true # won't delete your existing labels
          dry-run: false
          exclude: 